name: Trigger External Workflow

on:
  push:
    branches:
      - main

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow in another repository
        env:
          TOK: ${{ secrets.TEST_PAT }}
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token $TOK" \
          https://api.github.com/repos/dixitrit/CFT/dispatches \
          -d '{"event_type":"custom_event"}'
